theme: jekyll-theme-minimal
title: A Spectral Filter Predictor with Progressive Feedback
description: A Spectral Filter Predictor (SFP) with Progressive Feedback Method for Latent Fingerprint Restoration