theme: jekyll-theme-minimal
title: A Spectral Filter Predictor with Progressive Feedback
description: SFP: A Spectral Filter Predictor with Progressive Feedback Method for Latent Fingerprint Restoration